/**
 * Fase 25 — Catálogo de KPIs Supply Chain (fontes canônicas, sem inventar).
 */

import type { SupplyKpiDefinition } from "./types.ts";

export const SUPPLY_KPI_CATALOG: readonly SupplyKpiDefinition[] = [
  {
    id: "supply.giro",
    name: "Giro de estoque",
    unit: "ratio",
    formula: "consumo_periodo / estoque_médio (quando ambos canônicos)",
    source: "executive-stock-compose · estoque_movimentacoes",
    polarity: "higher_is_better",
    availability: "available",
    drillDownAvailable: true,
  },
  {
    id: "supply.cobertura",
    name: "Cobertura (dias)",
    unit: "days",
    formula: "saldo / consumo_médio_diário (90d)",
    source: "executive-stock-compose",
    polarity: "neutral",
    availability: "available",
    drillDownAvailable: true,
  },
  {
    id: "supply.ruptura",
    name: "Rupturas",
    unit: "count",
    formula: "produtos com saldo <= 0 ou abaixo do mínimo",
    source: "produtos + estoque",
    polarity: "lower_is_better",
    availability: "available",
    drillDownAvailable: true,
  },
  {
    id: "supply.excesso",
    name: "Excesso",
    unit: "count",
    formula: "produtos com saldo > estoque_máximo (quando máximo definido)",
    source: "produtos",
    polarity: "lower_is_better",
    availability: "available",
    drillDownAvailable: true,
  },
  {
    id: "supply.curva_abc",
    name: "Curva ABC (classe A)",
    unit: "count",
    formula: "itens classe A por valor de estoque / consumo",
    source: "executive-stock-compose ranking",
    polarity: "neutral",
    availability: "available",
    drillDownAvailable: true,
  },
  {
    id: "supply.parado",
    name: "Estoque parado",
    unit: "count",
    formula: "sem movimentação ≥ 90 dias com saldo > 0",
    source: "executive-stock-compose",
    polarity: "lower_is_better",
    availability: "available",
    drillDownAvailable: true,
  },
  {
    id: "supply.compras_mes",
    name: "Compras do mês",
    unit: "currency",
    formula: "soma pedidos_compra no mês (quando tabela existir)",
    source: "compras_pedidos",
    polarity: "neutral",
    availability: "available",
    drillDownAvailable: true,
  },
  {
    id: "supply.fornecedores",
    name: "Fornecedores ativos",
    unit: "count",
    formula: "count fornecedores ativos (Finance Core)",
    source: "lib/financeiro/fornecedor-service",
    polarity: "neutral",
    availability: "available",
    drillDownAvailable: true,
  },
  {
    id: "supply.consumo",
    name: "Consumo do período",
    unit: "count",
    formula: "soma saídas no período",
    source: "estoque_movimentacoes",
    polarity: "neutral",
    availability: "available",
    drillDownAvailable: true,
  },
  {
    id: "supply.margem",
    name: "Margem média",
    unit: "percent",
    formula: "(preço − custo) / preço — produtos com ambos",
    source: "produtos",
    polarity: "higher_is_better",
    availability: "available",
    drillDownAvailable: true,
  },
  {
    id: "supply.custo_medio",
    name: "Custo médio",
    unit: "currency",
    formula: "média ponderada de produtos.custo com saldo",
    source: "produtos",
    polarity: "neutral",
    availability: "available",
    drillDownAvailable: false,
  },
  {
    id: "supply.valorizacao",
    name: "Valorização do estoque",
    unit: "currency",
    formula: "soma saldo × custo (quando custo disponível)",
    source: "produtos",
    polarity: "neutral",
    availability: "available",
    drillDownAvailable: true,
  },
  {
    id: "supply.perdas",
    name: "Perdas",
    unit: "currency",
    formula: "movimentações tipo perda × custo",
    source: "estoque_movimentacoes (origem/motivo perda)",
    polarity: "lower_is_better",
    availability: "available",
    drillDownAvailable: true,
  },
  {
    id: "supply.inventario",
    name: "Divergências de inventário",
    unit: "count",
    formula: "itens com divergência em ciclos abertos",
    source: "inventarios (migration 20260813)",
    polarity: "lower_is_better",
    availability: "available",
    drillDownAvailable: true,
  },
];

export function getSupplyKpiDefinition(
  id: string,
): SupplyKpiDefinition | undefined {
  return SUPPLY_KPI_CATALOG.find((k) => k.id === id);
}
