/**
 * Fase 24 — Catálogo de KPIs CRM (fontes canônicas, sem inventar).
 */

import type { CrmKpiDefinition } from "./types.ts";

export const CRM_KPI_CATALOG: readonly CrmKpiDefinition[] = [
  {
    id: "crm.novos",
    name: "Novos clientes",
    unit: "count",
    formula: "CrmDashboardKpis.novos_clientes | CrmExecKpis.novosMes",
    source: "lib/crm/cliente-360-service · crm-executivo-compose",
    polarity: "higher_is_better",
    availability: "available",
    drillDownAvailable: true,
  },
  {
    id: "crm.ativos",
    name: "Clientes ativos",
    unit: "count",
    formula: "CrmDashboardKpis.clientes_ativos | CrmExecKpis.clientesAtivos",
    source: "CRM Executivo / Dashboard",
    polarity: "higher_is_better",
    availability: "available",
    drillDownAvailable: true,
  },
  {
    id: "crm.inativos",
    name: "Clientes inativos",
    unit: "count",
    formula: "CrmDashboardKpis.clientes_inativos | CrmExecKpis.inativos",
    source: "CRM Executivo (regra 180d)",
    polarity: "lower_is_better",
    availability: "available",
    drillDownAvailable: true,
  },
  {
    id: "crm.conversao",
    name: "Conversão do funil",
    unit: "percent",
    formula: "fechado / (fechado + perdido + em aberto) — CrmDashboardKpis.taxa_conversao",
    source: "CrmDashboardService",
    polarity: "higher_is_better",
    availability: "available",
    drillDownAvailable: true,
  },
  {
    id: "crm.ticket_medio",
    name: "Ticket médio",
    unit: "currency",
    formula: "CrmDashboardKpis.ticket_medio | CrmExecKpis.ticketMedioPorCliente",
    source: "Vendas/OS faturadas agregadas no CRM",
    polarity: "higher_is_better",
    availability: "available",
    drillDownAvailable: true,
  },
  {
    id: "crm.faturamento_cliente",
    name: "Faturamento por cliente",
    unit: "currency",
    formula: "CrmDashboardKpis.receita_por_cliente",
    source: "CRM Dashboard / Executivo",
    polarity: "higher_is_better",
    availability: "available",
    drillDownAvailable: true,
  },
  {
    id: "crm.recorrencia",
    name: "Clientes recorrentes",
    unit: "count",
    formula: "CrmDashboardKpis.clientes_recorrentes | CrmExecKpis.recorrentes",
    source: "CRM Executivo",
    polarity: "higher_is_better",
    availability: "available",
    drillDownAvailable: true,
  },
  {
    id: "crm.retencao",
    name: "Retenção",
    unit: "percent",
    formula: "—",
    source: "—",
    polarity: "higher_is_better",
    availability: "unavailable",
    unavailableReason:
      "Retenção exige coorte canônica de períodos — Dados indisponíveis até fonte dedicada.",
    drillDownAvailable: false,
  },
  {
    id: "crm.perda",
    name: "Clientes perdidos",
    unit: "count",
    formula: "CrmDashboardKpis.clientes_perdidos (estagio_funil=perdido)",
    source: "Funil CRM",
    polarity: "lower_is_better",
    availability: "available",
    drillDownAvailable: true,
  },
  {
    id: "crm.tempo_fechamento",
    name: "Tempo médio de fechamento",
    unit: "days",
    formula: "CrmDashboardKpis.tempo_medio_fechamento_dias",
    source: "CrmDashboardService",
    polarity: "lower_is_better",
    availability: "available",
    drillDownAvailable: true,
  },
  {
    id: "crm.oportunidades_abertas",
    name: "Oportunidades abertas",
    unit: "count",
    formula: "Cards em proposta+negociacao (ou oportunidades derivadas do Executivo)",
    source: "Funil + CrmExecOportunidades",
    polarity: "neutral",
    availability: "available",
    drillDownAvailable: true,
  },
  {
    id: "crm.valor_negociacao",
    name: "Valor em negociação",
    unit: "currency",
    formula: "Sum valor_pipeline etapas proposta/negociacao",
    source: "CrmFunilService column stats",
    polarity: "higher_is_better",
    availability: "available",
    drillDownAvailable: true,
  },
] as const;

export function getCrmKpiDefinition(id: string): CrmKpiDefinition | undefined {
  return CRM_KPI_CATALOG.find((k) => k.id === id);
}
