/**
 * Fase 23 — Catálogo central de métricas.
 * availability=unavailable quando não há fonte confiável — sem estimativa silenciosa.
 */

import type { MetricDefinition } from "../core/metric-types.ts";

function def(
  partial: Omit<MetricDefinition, "supportsDrillDown" | "supportsTarget"> & {
    supportsDrillDown?: boolean;
    supportsTarget?: boolean;
  },
): MetricDefinition {
  return {
    supportsDrillDown: partial.supportsDrillDown ?? true,
    supportsTarget: partial.supportsTarget ?? false,
    ...partial,
  };
}

export const METRIC_CATALOG: readonly MetricDefinition[] = [
  // —— FINANCEIRO (DRE / FI / Cash) ——
  def({
    id: "fin.receita_bruta",
    name: "Faturamento / Receita bruta",
    description: "Receita bruta do DRE no período.",
    formula: "DreResumo.receita_bruta (lib/financeiro/dre-service)",
    source: "lib/financeiro/dre-service + financial-intelligence",
    area: "financeiro",
    unit: "currency",
    polarity: "higher_is_better",
    dimensions: ["periodo", "centro_custo", "categoria", "empresa", "filial"],
    requiredPermission: "analytics.financeiro",
    availability: "available",
    supportsTarget: true,
  }),
  def({
    id: "fin.receita_liquida",
    name: "Receita líquida",
    description: "Receita líquida do DRE.",
    formula: "DreResumo.receita_liquida",
    source: "lib/financeiro/dre-service",
    area: "financeiro",
    unit: "currency",
    polarity: "higher_is_better",
    dimensions: ["periodo", "centro_custo", "categoria"],
    requiredPermission: "analytics.financeiro",
    availability: "available",
    supportsTarget: true,
  }),
  def({
    id: "fin.entradas",
    name: "Entradas de caixa",
    description: "Entradas realizadas no fluxo / camadas Cash Intelligence.",
    formula: "CashLayers.totals.realizedIn ou FluxoCaixaResumo entradas",
    source: "lib/finance/cash-intelligence | lib/financeiro/fluxo-caixa-service",
    area: "financeiro",
    unit: "currency",
    polarity: "higher_is_better",
    dimensions: ["periodo", "centro_custo"],
    requiredPermission: "analytics.financeiro",
    availability: "available",
  }),
  def({
    id: "fin.saidas",
    name: "Saídas de caixa",
    description: "Saídas realizadas.",
    formula: "CashLayers.totals.realizedOut",
    source: "lib/finance/cash-intelligence",
    area: "financeiro",
    unit: "currency",
    polarity: "lower_is_better",
    dimensions: ["periodo", "centro_custo"],
    requiredPermission: "analytics.financeiro",
    availability: "available",
  }),
  def({
    id: "fin.saldo_consolidado",
    name: "Saldo consolidado",
    description: "Saldo bancário consolidado.",
    formula: "computeConsolidatedBalance.consolidated",
    source: "lib/finance/cash-intelligence",
    area: "financeiro",
    unit: "currency",
    polarity: "higher_is_better",
    dimensions: ["empresa", "filial"],
    requiredPermission: "analytics.financeiro",
    availability: "available",
  }),
  def({
    id: "fin.ebitda",
    name: "EBITDA",
    description: "EBITDA do DRE.",
    formula: "DreResumo.ebitda",
    source: "lib/financeiro/dre-service",
    area: "financeiro",
    unit: "currency",
    polarity: "higher_is_better",
    dimensions: ["periodo", "centro_custo"],
    requiredPermission: "analytics.financeiro",
    availability: "available",
  }),
  def({
    id: "fin.margem_ebitda",
    name: "Margem EBITDA",
    description: "EBITDA / receita líquida.",
    formula: "FiMetric margem_ebitda (financial-intelligence)",
    source: "lib/financial-intelligence",
    area: "financeiro",
    unit: "percent",
    polarity: "higher_is_better",
    dimensions: ["periodo"],
    requiredPermission: "analytics.financeiro",
    availability: "available",
  }),
  def({
    id: "fin.lucro_operacional",
    name: "Lucro operacional (EBIT)",
    description: "EBIT do DRE.",
    formula: "DreResumo.ebit",
    source: "lib/financeiro/dre-service",
    area: "financeiro",
    unit: "currency",
    polarity: "higher_is_better",
    dimensions: ["periodo"],
    requiredPermission: "analytics.financeiro",
    availability: "available",
  }),
  def({
    id: "fin.lucro_liquido",
    name: "Lucro líquido",
    description: "Resultado líquido / final do DRE.",
    formula: "DreResumo.resultado_final | resultado_liquido",
    source: "lib/financeiro/dre-service",
    area: "financeiro",
    unit: "currency",
    polarity: "higher_is_better",
    dimensions: ["periodo"],
    requiredPermission: "analytics.financeiro",
    availability: "available",
  }),
  def({
    id: "fin.despesas",
    name: "Despesas operacionais",
    description: "OPEX do DRE.",
    formula: "DreResumo.despesas_operacionais",
    source: "lib/financeiro/dre-service",
    area: "financeiro",
    unit: "currency",
    polarity: "lower_is_better",
    dimensions: ["periodo", "categoria", "centro_custo"],
    requiredPermission: "analytics.financeiro",
    availability: "available",
  }),
  def({
    id: "fin.custos",
    name: "CMV / Custos",
    description: "Custo das mercadorias/serviços vendidos.",
    formula: "DreResumo.cmv",
    source: "lib/financeiro/dre-service",
    area: "financeiro",
    unit: "currency",
    polarity: "lower_is_better",
    dimensions: ["periodo"],
    requiredPermission: "analytics.financeiro",
    availability: "available",
  }),
  def({
    id: "fin.capital_giro",
    name: "Capital de giro",
    description: "Working capital recomendado / snapshot Cash Intelligence.",
    formula: "computeWorkingCapital (cash-intelligence)",
    source: "lib/finance/cash-intelligence",
    area: "financeiro",
    unit: "currency",
    polarity: "higher_is_better",
    dimensions: ["periodo"],
    requiredPermission: "analytics.financeiro",
    availability: "available",
  }),
  def({
    id: "fin.contas_pagar",
    name: "Contas a pagar abertas",
    description: "Soma de títulos a pagar pendentes.",
    formula: "Sum OpenTitleSnapshot payable.amountPending",
    source: "lib/finance/cash-intelligence snapshot",
    area: "financeiro",
    unit: "currency",
    polarity: "lower_is_better",
    dimensions: ["periodo", "fornecedor", "status"],
    requiredPermission: "analytics.financeiro",
    availability: "available",
  }),
  def({
    id: "fin.contas_receber",
    name: "Contas a receber abertas",
    description: "Soma de títulos a receber pendentes.",
    formula: "Sum OpenTitleSnapshot receivable.amountPending",
    source: "lib/finance/cash-intelligence snapshot",
    area: "financeiro",
    unit: "currency",
    polarity: "higher_is_better",
    dimensions: ["periodo", "cliente", "status"],
    requiredPermission: "analytics.financeiro",
    availability: "available",
  }),
  def({
    id: "fin.inadimplencia",
    name: "Inadimplência (vencidos a receber)",
    description: "Recebíveis vencidos pendentes.",
    formula: "Sum receivable overdue amountPending",
    source: "lib/finance/cash-intelligence snapshot",
    area: "financeiro",
    unit: "currency",
    polarity: "lower_is_better",
    dimensions: ["cliente", "periodo"],
    requiredPermission: "analytics.financeiro",
    availability: "available",
  }),
  def({
    id: "fin.pmr",
    name: "Prazo médio de recebimento",
    description: "PMR formal.",
    formula: "—",
    source: "não disponível",
    area: "financeiro",
    unit: "days",
    polarity: "lower_is_better",
    dimensions: ["periodo"],
    requiredPermission: "analytics.financeiro",
    availability: "unavailable",
    unavailableReason:
      "Não há serviço canônico de PMR no Finance Core nesta versão.",
    supportsDrillDown: false,
  }),
  def({
    id: "fin.pmp",
    name: "Prazo médio de pagamento",
    description: "PMP formal.",
    formula: "—",
    source: "não disponível",
    area: "financeiro",
    unit: "days",
    polarity: "neutral",
    dimensions: ["periodo"],
    requiredPermission: "analytics.financeiro",
    availability: "unavailable",
    unavailableReason:
      "Não há serviço canônico de PMP no Finance Core nesta versão.",
    supportsDrillDown: false,
  }),
  def({
    id: "fin.fluxo_realizado",
    name: "Fluxo realizado",
    description: "Camada REALIZADO do Cash Intelligence.",
    formula: "layers.totals realized in/out",
    source: "lib/finance/cash-intelligence",
    area: "financeiro",
    unit: "currency",
    polarity: "neutral",
    dimensions: ["periodo"],
    requiredPermission: "analytics.financeiro",
    availability: "available",
  }),
  def({
    id: "fin.fluxo_previsto",
    name: "Fluxo previsto",
    description: "Camada PREVISTO (AP/AR/recorrências).",
    formula: "layers.totals forecast",
    source: "lib/finance/cash-intelligence",
    area: "financeiro",
    unit: "currency",
    polarity: "neutral",
    dimensions: ["periodo"],
    requiredPermission: "analytics.financeiro",
    availability: "available",
  }),
  def({
    id: "fin.fluxo_projetado",
    name: "Fluxo projetado",
    description: "Camada PROJETADO / projectCashflow.",
    formula: "projectCashflow closing/net",
    source: "lib/finance/cash-intelligence",
    area: "financeiro",
    unit: "currency",
    polarity: "higher_is_better",
    dimensions: ["periodo"],
    requiredPermission: "analytics.financeiro",
    availability: "available",
  }),
  def({
    id: "fin.necessidade_caixa",
    name: "Necessidade de caixa / risco",
    description: "Alertas de ruptura / capital mínimo.",
    formula: "CashRiskAlerts + workingCapital.recommended",
    source: "lib/finance/cash-intelligence",
    area: "financeiro",
    unit: "currency",
    polarity: "lower_is_better",
    dimensions: ["periodo"],
    requiredPermission: "analytics.financeiro",
    availability: "available",
  }),

  // —— VENDAS ——
  def({
    id: "vendas.faturamento",
    name: "Faturamento comercial",
    description: "Faturamento do Commercial Intelligence / metas.",
    formula: "CiKpis.faturamento | aggregateFaturamentoLiquido",
    source: "lib/vendas/commercial-intelligence-*",
    area: "vendas",
    unit: "currency",
    polarity: "higher_is_better",
    dimensions: ["periodo", "vendedor", "filial", "canal", "produto"],
    requiredPermission: "analytics.vendas",
    availability: "available",
    supportsTarget: true,
  }),
  def({
    id: "vendas.quantidade",
    name: "Quantidade de vendas",
    description: "Vendas faturadas no período.",
    formula: "CiKpis.quantidadeFaturadas",
    source: "lib/vendas/commercial-intelligence-*",
    area: "vendas",
    unit: "count",
    polarity: "higher_is_better",
    dimensions: ["periodo", "vendedor", "filial"],
    requiredPermission: "analytics.vendas",
    availability: "available",
  }),
  def({
    id: "vendas.ticket_medio",
    name: "Ticket médio",
    description: "Faturamento / quantidade.",
    formula: "CiKpis.ticketMedio",
    source: "lib/vendas/commercial-intelligence-*",
    area: "vendas",
    unit: "currency",
    polarity: "higher_is_better",
    dimensions: ["periodo", "canal"],
    requiredPermission: "analytics.vendas",
    availability: "available",
  }),
  def({
    id: "vendas.conversao",
    name: "Taxa de conversão",
    description: "Conversão de orçamentos.",
    formula: "CiKpis.taxaConversao",
    source: "lib/vendas/commercial-intelligence-*",
    area: "vendas",
    unit: "percent",
    polarity: "higher_is_better",
    dimensions: ["periodo", "canal"],
    requiredPermission: "analytics.vendas",
    availability: "available",
  }),
  def({
    id: "vendas.cancelamentos",
    name: "Cancelamentos",
    description: "Vendas/orçamentos cancelados.",
    formula: "CiKpis.canceladas",
    source: "lib/vendas/commercial-intelligence-*",
    area: "vendas",
    unit: "count",
    polarity: "lower_is_better",
    dimensions: ["periodo"],
    requiredPermission: "analytics.vendas",
    availability: "available",
  }),
  def({
    id: "vendas.descontos",
    name: "Descontos",
    description: "Valor de descontos concedidos.",
    formula: "CiKpis.desconto",
    source: "lib/vendas/commercial-intelligence-*",
    area: "vendas",
    unit: "currency",
    polarity: "lower_is_better",
    dimensions: ["periodo", "vendedor"],
    requiredPermission: "analytics.vendas",
    availability: "available",
  }),
  def({
    id: "vendas.por_vendedor",
    name: "Vendas por vendedor",
    description: "Ranking comercial por vendedor.",
    formula: "Commercial Intelligence rankings",
    source: "lib/vendas/commercial-intelligence-*",
    area: "vendas",
    unit: "currency",
    polarity: "higher_is_better",
    dimensions: ["vendedor", "periodo"],
    requiredPermission: "analytics.vendas",
    availability: "available",
  }),
  def({
    id: "vendas.por_cliente",
    name: "Vendas por cliente",
    description: "Ranking por cliente.",
    formula: "Commercial / FI topClientes",
    source: "lib/vendas + financial-intelligence",
    area: "vendas",
    unit: "currency",
    polarity: "higher_is_better",
    dimensions: ["cliente", "periodo"],
    requiredPermission: "analytics.vendas",
    availability: "available",
  }),
  def({
    id: "vendas.por_produto",
    name: "Vendas por produto",
    description: "Ranking por produto.",
    formula: "Commercial Intelligence product ranking",
    source: "lib/vendas/commercial-intelligence-*",
    area: "vendas",
    unit: "currency",
    polarity: "higher_is_better",
    dimensions: ["produto", "periodo"],
    requiredPermission: "analytics.vendas",
    availability: "partial",
    unavailableReason:
      "Depende do ranking de produtos no snapshot comercial; ausente = indisponível.",
  }),
  def({
    id: "vendas.por_filial",
    name: "Vendas por filial",
    description: "Consolidação por filial/centro.",
    formula: "Commercial panel centros / filtros",
    source: "lib/metas/commercial-panel-service",
    area: "vendas",
    unit: "currency",
    polarity: "higher_is_better",
    dimensions: ["filial", "periodo"],
    requiredPermission: "analytics.vendas",
    availability: "partial",
  }),
  def({
    id: "vendas.por_canal",
    name: "Vendas por canal",
    description: "Faturamento por canal.",
    formula: "CommercialPanel canais",
    source: "lib/metas/commercial-panel-service",
    area: "vendas",
    unit: "currency",
    polarity: "higher_is_better",
    dimensions: ["canal", "periodo"],
    requiredPermission: "analytics.vendas",
    availability: "partial",
  }),
  def({
    id: "vendas.margem",
    name: "Margem por venda",
    description: "Margem bruta comercial quando disponível.",
    formula: "VendasDashboardService.margemBruta (órfão) / CI se expuser",
    source: "lib/vendas",
    area: "vendas",
    unit: "currency",
    polarity: "higher_is_better",
    dimensions: ["periodo"],
    requiredPermission: "analytics.vendas",
    availability: "partial",
  }),
  def({
    id: "vendas.recorrencia",
    name: "Recorrência de vendas",
    description: "Clientes recorrentes no comercial.",
    formula: "—",
    source: "parcial via CRM",
    area: "vendas",
    unit: "ratio",
    polarity: "higher_is_better",
    dimensions: ["periodo"],
    requiredPermission: "analytics.vendas",
    availability: "unavailable",
    unavailableReason:
      "Recorrência de vendas não é KPI canônico no Commercial Intelligence; use clientes.recorrentes.",
    supportsDrillDown: false,
  }),
  def({
    id: "vendas.crescimento",
    name: "Crescimento comercial",
    description: "Variação vs período anterior (comparativo).",
    formula: "compareMetric(vendas.faturamento)",
    source: "analytics comparison-engine sobre CI",
    area: "vendas",
    unit: "percent",
    polarity: "higher_is_better",
    dimensions: ["periodo"],
    requiredPermission: "analytics.vendas",
    availability: "available",
  }),

  // —— CLIENTES ——
  def({
    id: "clientes.ativos",
    name: "Clientes ativos",
    description: "Carteira ativa CRM executivo.",
    formula: "CrmExecKpis.clientesAtivos",
    source: "lib/crm/crm-executivo-*",
    area: "clientes",
    unit: "count",
    polarity: "higher_is_better",
    dimensions: ["periodo"],
    requiredPermission: "analytics.operacional",
    availability: "available",
  }),
  def({
    id: "clientes.novos",
    name: "Clientes novos",
    description: "Novos no mês.",
    formula: "CrmExecKpis.novosMes",
    source: "lib/crm/crm-executivo-*",
    area: "clientes",
    unit: "count",
    polarity: "higher_is_better",
    dimensions: ["periodo"],
    requiredPermission: "analytics.operacional",
    availability: "available",
  }),
  def({
    id: "clientes.recorrentes",
    name: "Clientes recorrentes",
    description: "Recorrentes na carteira.",
    formula: "CrmExecKpis.recorrentes",
    source: "lib/crm/crm-executivo-*",
    area: "clientes",
    unit: "count",
    polarity: "higher_is_better",
    dimensions: ["periodo"],
    requiredPermission: "analytics.operacional",
    availability: "available",
  }),
  def({
    id: "clientes.inativos",
    name: "Clientes inativos",
    description: "Inativos 180d.",
    formula: "CrmExecKpis.inativos180",
    source: "lib/crm/crm-executivo-*",
    area: "clientes",
    unit: "count",
    polarity: "lower_is_better",
    dimensions: ["periodo"],
    requiredPermission: "analytics.operacional",
    availability: "available",
  }),
  def({
    id: "clientes.frequencia",
    name: "Frequência / visitas",
    description: "Média de visitas.",
    formula: "CrmExecKpis.mediaVisitas",
    source: "lib/crm/crm-executivo-*",
    area: "clientes",
    unit: "ratio",
    polarity: "higher_is_better",
    dimensions: ["periodo"],
    requiredPermission: "analytics.operacional",
    availability: "available",
  }),
  def({
    id: "clientes.ticket_medio",
    name: "Ticket médio por cliente",
    description: "Ticket médio CRM.",
    formula: "CrmExecKpis.ticketMedioPorCliente",
    source: "lib/crm/crm-executivo-*",
    area: "clientes",
    unit: "currency",
    polarity: "higher_is_better",
    dimensions: ["periodo"],
    requiredPermission: "analytics.operacional",
    availability: "available",
  }),
  def({
    id: "clientes.receita",
    name: "Receita por cliente",
    description: "Faturamento por cliente (carteira).",
    formula: "CrmExecKpis.faturamentoPorCliente",
    source: "lib/crm/crm-executivo-*",
    area: "clientes",
    unit: "currency",
    polarity: "higher_is_better",
    dimensions: ["cliente", "periodo"],
    requiredPermission: "analytics.operacional",
    availability: "available",
  }),
  def({
    id: "clientes.ltv",
    name: "LTV",
    description: "Lifetime value formal.",
    formula: "—",
    source: "não disponível",
    area: "clientes",
    unit: "currency",
    polarity: "higher_is_better",
    dimensions: ["cliente"],
    requiredPermission: "analytics.operacional",
    availability: "unavailable",
    unavailableReason:
      "LTV formal não está implementado; use totalGastoLifetime do CRM como proxy apenas na UI CRM, não como LTV.",
    supportsDrillDown: false,
  }),
  def({
    id: "clientes.retencao",
    name: "Retenção",
    description: "Taxa de retenção formal.",
    formula: "—",
    source: "não disponível",
    area: "clientes",
    unit: "percent",
    polarity: "higher_is_better",
    dimensions: ["periodo"],
    requiredPermission: "analytics.operacional",
    availability: "unavailable",
    unavailableReason: "Sem cohort de retenção canônico no CRM executivo.",
    supportsDrillDown: false,
  }),
  def({
    id: "clientes.recompra",
    name: "Recompra",
    description: "Taxa de recompra.",
    formula: "—",
    source: "não disponível",
    area: "clientes",
    unit: "percent",
    polarity: "higher_is_better",
    dimensions: ["periodo"],
    requiredPermission: "analytics.operacional",
    availability: "unavailable",
    unavailableReason: "Sem métrica canônica de recompra.",
    supportsDrillDown: false,
  }),
  def({
    id: "clientes.concentracao",
    name: "Concentração de receita",
    description: "Concentração top clientes (quando ranking disponível).",
    formula: "Share top1 / total a partir do ranking comercial",
    source: "lib/vendas commercial ranking (byClient)",
    area: "clientes",
    unit: "percent",
    polarity: "lower_is_better",
    dimensions: ["periodo"],
    requiredPermission: "analytics.operacional",
    availability: "partial",
    unavailableReason:
      "Concentração exige ranking de clientes; ausente = Dados indisponíveis.",
  }),
  def({
    id: "clientes.risco",
    name: "Clientes em risco",
    description: "Riscos CRM executivo.",
    formula: "composeCrmExecRiscos count",
    source: "lib/crm/crm-executivo-*",
    area: "clientes",
    unit: "count",
    polarity: "lower_is_better",
    dimensions: ["cliente"],
    requiredPermission: "analytics.operacional",
    availability: "available",
  }),

  // —— OS ——
  def({
    id: "os.quantidade",
    name: "Quantidade de OS",
    description: "Total de OS no recorte do dashboard.",
    formula: "Soma status OsDashboardKpis",
    source: "lib/ordens/os-dashboard-service",
    area: "operacoes",
    unit: "count",
    polarity: "neutral",
    dimensions: ["periodo", "status", "unidade"],
    requiredPermission: "analytics.operacional",
    availability: "available",
  }),
  def({
    id: "os.abertas",
    name: "OS abertas",
    description: "OS em aberto.",
    formula: "OsDashboardKpis.abertas",
    source: "lib/ordens/os-dashboard-service",
    area: "operacoes",
    unit: "count",
    polarity: "neutral",
    dimensions: ["status"],
    requiredPermission: "analytics.operacional",
    availability: "available",
  }),
  def({
    id: "os.concluidas",
    name: "OS concluídas",
    description: "OS finalizadas.",
    formula: "OsDashboardKpis.finalizadas",
    source: "lib/ordens/os-dashboard-service",
    area: "operacoes",
    unit: "count",
    polarity: "higher_is_better",
    dimensions: ["periodo"],
    requiredPermission: "analytics.operacional",
    availability: "available",
  }),
  def({
    id: "os.tempo_medio",
    name: "Tempo médio de conclusão",
    description: "Dias médios até conclusão.",
    formula: "OsDashboardKpis.tempoMedioConclusaoDias",
    source: "lib/ordens/os-dashboard-service",
    area: "operacoes",
    unit: "days",
    polarity: "lower_is_better",
    dimensions: ["periodo"],
    requiredPermission: "analytics.operacional",
    availability: "available",
  }),
  def({
    id: "os.produtividade",
    name: "Produtividade (mecânicos)",
    description: "Indicadores do dashboard de mecânicos.",
    formula: "mecanicos-dashboard-service KPIs",
    source: "lib/operacoes/mecanicos-dashboard-service",
    area: "operacoes",
    unit: "score",
    polarity: "higher_is_better",
    dimensions: ["responsavel", "unidade"],
    requiredPermission: "analytics.operacional",
    availability: "partial",
  }),
  def({
    id: "os.retrabalho",
    name: "Retrabalho",
    description: "Índice de retrabalho.",
    formula: "OsDashboardKpis.indiceRetrabalho",
    source: "lib/ordens/os-dashboard-service",
    area: "operacoes",
    unit: "ratio",
    polarity: "lower_is_better",
    dimensions: ["periodo"],
    requiredPermission: "analytics.operacional",
    availability: "available",
  }),
  def({
    id: "os.conversao_orcamento",
    name: "Conversão de orçamento (OS)",
    description: "Taxa de aprovação.",
    formula: "OsDashboardKpis.taxaAprovacao",
    source: "lib/ordens/os-dashboard-service",
    area: "operacoes",
    unit: "percent",
    polarity: "higher_is_better",
    dimensions: ["periodo"],
    requiredPermission: "analytics.operacional",
    availability: "available",
  }),
  def({
    id: "os.faturamento",
    name: "Faturamento por OS",
    description: "Faturamento agregado de OS.",
    formula: "OsDashboardKpis.faturamento",
    source: "lib/ordens/os-dashboard-service",
    area: "operacoes",
    unit: "currency",
    polarity: "higher_is_better",
    dimensions: ["periodo", "unidade"],
    requiredPermission: "analytics.operacional",
    availability: "available",
  }),
  def({
    id: "os.ticket_medio",
    name: "Ticket médio OS",
    description: "Ticket médio das OS no período.",
    formula: "OsDashboardKpis.ticketMedio",
    source: "lib/ordens/os-dashboard-service",
    area: "operacoes",
    unit: "currency",
    polarity: "higher_is_better",
    dimensions: ["periodo"],
    requiredPermission: "analytics.operacional",
    availability: "available",
  }),
  def({
    id: "os.margem",
    name: "Margem por OS",
    description: "Margem operacional por OS.",
    formula: "—",
    source: "não disponível de forma canônica no OS dashboard",
    area: "operacoes",
    unit: "currency",
    polarity: "higher_is_better",
    dimensions: ["periodo"],
    requiredPermission: "analytics.operacional",
    availability: "unavailable",
    unavailableReason:
      "Margem por OS não é KPI exportado pelo os-dashboard-service; FI marca receita_por_os unavailable.",
    supportsDrillDown: false,
  }),
  def({
    id: "os.servicos_mais_vendidos",
    name: "Serviços mais vendidos",
    description: "Ranking por tipo de serviço.",
    formula: "OsDashboard porTipoServico",
    source: "lib/ordens/os-dashboard-service",
    area: "operacoes",
    unit: "count",
    polarity: "higher_is_better",
    dimensions: ["servico", "periodo"],
    requiredPermission: "analytics.operacional",
    availability: "available",
  }),

  // —— ESTOQUE ——
  def({
    id: "estoque.valor",
    name: "Valor do estoque",
    description: "Valor total em estoque.",
    formula: "ExecutiveStock.valorTotalEstoque",
    source: "lib/estoque/executive-stock-service",
    area: "estoque",
    unit: "currency",
    polarity: "neutral",
    dimensions: ["filial", "produto"],
    requiredPermission: "analytics.estoque",
    availability: "available",
  }),
  def({
    id: "estoque.giro",
    name: "Giro de estoque",
    description: "Giro médio.",
    formula: "ExecutiveStock.giroMedio",
    source: "lib/estoque/executive-stock-service",
    area: "estoque",
    unit: "ratio",
    polarity: "higher_is_better",
    dimensions: ["periodo", "produto"],
    requiredPermission: "analytics.estoque",
    availability: "available",
  }),
  def({
    id: "estoque.cobertura",
    name: "Cobertura de estoque",
    description: "Cobertura em dias/período.",
    formula: "ExecutiveStock.coberturaEstoque",
    source: "lib/estoque/executive-stock-service",
    area: "estoque",
    unit: "days",
    polarity: "neutral",
    dimensions: ["produto"],
    requiredPermission: "analytics.estoque",
    availability: "available",
  }),
  def({
    id: "estoque.ruptura",
    name: "Ruptura / zerados",
    description: "Produtos zerados / abaixo do mínimo.",
    formula: "produtosZerados + produtosAbaixoMinimo",
    source: "lib/estoque/executive-stock-service",
    area: "estoque",
    unit: "count",
    polarity: "lower_is_better",
    dimensions: ["produto", "filial"],
    requiredPermission: "analytics.estoque",
    availability: "available",
  }),
  def({
    id: "estoque.excesso",
    name: "Excesso / parado",
    description: "Valor financeiro parado.",
    formula: "ExecutiveStock.valorFinanceiroParado",
    source: "lib/estoque/executive-stock-service",
    area: "estoque",
    unit: "currency",
    polarity: "lower_is_better",
    dimensions: ["produto"],
    requiredPermission: "analytics.estoque",
    availability: "available",
  }),
  def({
    id: "estoque.itens_parados",
    name: "Itens parados",
    description: "SKUs sem giro (legado/executivo).",
    formula: "alertas / semGiro quando disponível",
    source: "lib/estoque/executive-stock-service",
    area: "estoque",
    unit: "count",
    polarity: "lower_is_better",
    dimensions: ["produto"],
    requiredPermission: "analytics.estoque",
    availability: "partial",
  }),
  def({
    id: "estoque.perdas",
    name: "Perdas de estoque",
    description: "Perdas formalizadas.",
    formula: "—",
    source: "não disponível",
    area: "estoque",
    unit: "currency",
    polarity: "lower_is_better",
    dimensions: ["periodo"],
    requiredPermission: "analytics.estoque",
    availability: "unavailable",
    unavailableReason: "Sem KPI canônico de perdas no executive-stock-service.",
    supportsDrillDown: false,
  }),
  def({
    id: "estoque.compras",
    name: "Compras / entradas",
    description: "Entradas no período (legado).",
    formula: "EstoqueDashboardService entradasPeriodo",
    source: "lib/estoque/estoque-dashboard-service",
    area: "estoque",
    unit: "currency",
    polarity: "neutral",
    dimensions: ["periodo", "fornecedor"],
    requiredPermission: "analytics.estoque",
    availability: "partial",
  }),
  def({
    id: "estoque.consumo",
    name: "Consumo / saídas",
    description: "Saídas no período.",
    formula: "EstoqueDashboardService saidasPeriodo",
    source: "lib/estoque/estoque-dashboard-service",
    area: "estoque",
    unit: "currency",
    polarity: "neutral",
    dimensions: ["periodo"],
    requiredPermission: "analytics.estoque",
    availability: "partial",
  }),
  def({
    id: "estoque.curva_abc",
    name: "Curva ABC",
    description: "Classificação ABC.",
    formula: "—",
    source: "não disponível",
    area: "estoque",
    unit: "score",
    polarity: "neutral",
    dimensions: ["produto"],
    requiredPermission: "analytics.estoque",
    availability: "unavailable",
    unavailableReason: "Curva ABC não implementada no estoque executivo.",
    supportsDrillDown: false,
  }),
  def({
    id: "estoque.margem_produto",
    name: "Margem por produto",
    description: "Margem potencial (legado).",
    formula: "EstoqueDashboardService.margemPotencial",
    source: "lib/estoque/estoque-dashboard-service",
    area: "estoque",
    unit: "currency",
    polarity: "higher_is_better",
    dimensions: ["produto"],
    requiredPermission: "analytics.estoque",
    availability: "partial",
  }),

  // —— TRIBUTÁRIO ——
  def({
    id: "tax.carga",
    name: "Carga tributária consolidada",
    description: "ExecutiveTaxDashboard.consolidatedLoad",
    formula: "buildExecutiveTaxDashboard.consolidatedLoad",
    source: "lib/finance/tax-intelligence",
    area: "tributario",
    unit: "currency",
    polarity: "lower_is_better",
    dimensions: ["periodo", "empresa", "filial", "regime"],
    requiredPermission: "analytics.tributario",
    availability: "available",
  }),
  def({
    id: "tax.por_regime",
    name: "Tributos por regime",
    description: "Drill regime.",
    formula: "buildTaxDrillDown dimension=regime",
    source: "lib/finance/tax-intelligence",
    area: "tributario",
    unit: "currency",
    polarity: "neutral",
    dimensions: ["regime"],
    requiredPermission: "analytics.tributario",
    availability: "available",
  }),
  def({
    id: "tax.por_filial",
    name: "Tributos por filial",
    description: "byBranch",
    formula: "ExecutiveTaxDashboard.byBranch",
    source: "lib/finance/tax-intelligence",
    area: "tributario",
    unit: "currency",
    polarity: "neutral",
    dimensions: ["filial"],
    requiredPermission: "analytics.tributario",
    availability: "available",
  }),
  def({
    id: "tax.impacto_caixa",
    name: "Impacto tributário no caixa",
    description: "projectTaxCashflow.totalTaxOutflow",
    formula: "projectTaxCashflow",
    source: "lib/finance/tax-intelligence",
    area: "tributario",
    unit: "currency",
    polarity: "lower_is_better",
    dimensions: ["periodo"],
    requiredPermission: "analytics.tributario",
    availability: "available",
  }),
  def({
    id: "tax.impacto_ebitda",
    name: "Impacto no EBITDA",
    description: "Carga / EBITDA proxy quando informado.",
    formula: "tax alerts ebitda_impact | ratio carga/EBITDA",
    source: "lib/finance/tax-intelligence + DRE",
    area: "tributario",
    unit: "ratio",
    polarity: "lower_is_better",
    dimensions: ["periodo"],
    requiredPermission: "analytics.tributario",
    availability: "partial",
  }),
  def({
    id: "tax.realizado",
    name: "Tributos realizados",
    description: "Carga consolidada realizada.",
    formula: "consolidatedLoad",
    source: "lib/finance/tax-intelligence",
    area: "tributario",
    unit: "currency",
    polarity: "neutral",
    dimensions: ["periodo"],
    requiredPermission: "analytics.tributario",
    availability: "available",
  }),
  def({
    id: "tax.previsto",
    name: "Tributos previstos",
    description: "Projetado informado no dashboard tributário.",
    formula: "projectedLoad",
    source: "lib/finance/tax-intelligence",
    area: "tributario",
    unit: "currency",
    polarity: "neutral",
    dimensions: ["periodo"],
    requiredPermission: "analytics.tributario",
    availability: "available",
  }),
  def({
    id: "tax.oportunidades",
    name: "Oportunidades tributárias",
    description: "Opportunities count/impact.",
    formula: "ExecutiveTaxDashboard.opportunities",
    source: "lib/finance/tax-intelligence",
    area: "tributario",
    unit: "currency",
    polarity: "higher_is_better",
    dimensions: ["periodo"],
    requiredPermission: "analytics.tributario",
    availability: "available",
  }),
  def({
    id: "tax.riscos",
    name: "Riscos fiscais",
    description: "Alertas tributários não-info.",
    formula: "buildTaxAlerts severity!=info",
    source: "lib/finance/tax-intelligence",
    area: "tributario",
    unit: "count",
    polarity: "lower_is_better",
    dimensions: ["periodo"],
    requiredPermission: "analytics.tributario",
    availability: "available",
  }),
  def({
    id: "tax.eficiencia",
    name: "Eficiência tributária",
    description: "Indicador effective_load.",
    formula: "efficiency effective_load",
    source: "lib/finance/tax-intelligence",
    area: "tributario",
    unit: "ratio",
    polarity: "lower_is_better",
    dimensions: ["periodo"],
    requiredPermission: "analytics.tributario",
    availability: "available",
  }),
] as const;

export function getMetricDefinition(id: string): MetricDefinition | undefined {
  return METRIC_CATALOG.find((m) => m.id === id);
}

export function listMetricsByArea(area: MetricDefinition["area"]) {
  return METRIC_CATALOG.filter((m) => m.area === area);
}

export function listAvailableMetrics() {
  return METRIC_CATALOG.filter((m) => m.availability !== "unavailable");
}
