import { calcMargemPercent } from "@/lib/produtos/format";
import type { ProdutoFormValues } from "@/lib/produtos/validations";
import type { CreateProdutoInput, Produto } from "@/types/produtos";
import { toNumericInputValue } from "@/lib/produtos/format";

export function normalizeProdutoFormValues(
  values: ProdutoFormValues,
): CreateProdutoInput {
  const custo = values.custo ?? null;
  const precoVenda = values.preco_venda ?? null;
  const isServico = values.tipo === "servico";

  return {
    nome: values.nome.trim(),
    tipo: values.tipo,
    codigo_interno: values.codigo_interno?.trim() || null,
    sku: values.sku?.trim() || null,
    codigo_barras: values.codigo_barras?.trim() || null,
    categoria: values.categoria?.trim() || null,
    subcategoria: values.subcategoria?.trim() || null,
    marca: values.marca?.trim() || null,
    fabricante: values.fabricante?.trim() || null,
    descricao_resumida: values.descricao_resumida?.trim() || null,
    unidade_medida: values.unidade_medida.trim(),
    ncm: values.ncm?.trim() || null,
    cest: values.cest?.trim() || null,
    origem_mercadoria: values.origem_mercadoria?.trim() || null,
    peso_kg: values.peso_kg ?? null,
    dimensoes: values.dimensoes?.trim() || null,
    altura_cm: values.altura_cm ?? null,
    largura_cm: values.largura_cm ?? null,
    comprimento_cm: values.comprimento_cm ?? null,
    custo,
    custo_reposicao: values.custo_reposicao ?? null,
    preco_venda: precoVenda,
    preco_minimo: values.preco_minimo ?? null,
    margem_alvo: values.margem_alvo ?? null,
    margem_percent: calcMargemPercent(custo, precoVenda),
    estoque_atual: isServico ? 0 : (values.estoque_atual ?? 0),
    estoque_minimo: isServico ? null : (values.estoque_minimo ?? null),
    estoque_maximo: isServico ? null : (values.estoque_maximo ?? null),
    estoque_seguranca: isServico ? null : (values.estoque_seguranca ?? null),
    localizacao: values.localizacao?.trim() || null,
    fornecedor_principal: values.fornecedor_principal?.trim() || null,
    fornecedor_alternativo: values.fornecedor_alternativo?.trim() || null,
    controla_estoque: isServico ? false : Boolean(values.controla_estoque),
    controla_lote: isServico ? false : Boolean(values.controla_lote),
    controla_serie: isServico ? false : Boolean(values.controla_serie),
    controla_validade: isServico ? false : Boolean(values.controla_validade),
    observacoes: values.observacoes?.trim() || null,
    ativo: values.ativo,
  };
}

export function produtoToFormValues(produto: Produto): ProdutoFormValues {
  return {
    nome: produto.nome,
    tipo: produto.tipo,
    codigo_interno: produto.codigo_interno ?? "",
    sku: produto.sku ?? "",
    codigo_barras: produto.codigo_barras ?? "",
    categoria: produto.categoria ?? "",
    subcategoria: produto.subcategoria ?? "",
    marca: produto.marca ?? "",
    fabricante: produto.fabricante ?? "",
    descricao_resumida: produto.descricao_resumida ?? "",
    unidade_medida: produto.unidade_medida,
    ncm: produto.ncm ?? "",
    cest: produto.cest ?? "",
    origem_mercadoria: produto.origem_mercadoria ?? "",
    peso_kg: produto.peso_kg,
    dimensoes: produto.dimensoes ?? "",
    altura_cm: produto.altura_cm,
    largura_cm: produto.largura_cm,
    comprimento_cm: produto.comprimento_cm,
    custo: produto.custo,
    custo_reposicao: produto.custo_reposicao,
    preco_venda: produto.preco_venda,
    preco_minimo: produto.preco_minimo,
    margem_alvo: produto.margem_alvo,
    estoque_atual: produto.estoque_atual,
    estoque_minimo: produto.estoque_minimo,
    estoque_maximo: produto.estoque_maximo,
    estoque_seguranca: produto.estoque_seguranca,
    localizacao: produto.localizacao ?? "",
    fornecedor_principal: produto.fornecedor_principal ?? "",
    fornecedor_alternativo: produto.fornecedor_alternativo ?? "",
    controla_estoque: produto.controla_estoque ?? produto.tipo !== "servico",
    controla_lote: produto.controla_lote ?? false,
    controla_serie: produto.controla_serie ?? false,
    controla_validade: produto.controla_validade ?? false,
    observacoes: produto.observacoes ?? "",
    ativo: produto.ativo,
  };
}

export function buildProdutoPayload(input: CreateProdutoInput) {
  return {
    nome: input.nome,
    tipo: input.tipo,
    codigo_interno: input.codigo_interno ?? null,
    sku: input.sku ?? null,
    codigo_barras: input.codigo_barras ?? null,
    categoria: input.categoria ?? null,
    subcategoria: input.subcategoria ?? null,
    marca: input.marca ?? null,
    fabricante: input.fabricante ?? null,
    descricao_resumida: input.descricao_resumida ?? null,
    unidade_medida: input.unidade_medida,
    ncm: input.ncm ?? null,
    cest: input.cest ?? null,
    origem_mercadoria: input.origem_mercadoria ?? null,
    peso_kg: input.peso_kg ?? null,
    dimensoes: input.dimensoes ?? null,
    altura_cm: input.altura_cm ?? null,
    largura_cm: input.largura_cm ?? null,
    comprimento_cm: input.comprimento_cm ?? null,
    custo: input.custo ?? null,
    custo_reposicao: input.custo_reposicao ?? null,
    preco_venda: input.preco_venda ?? null,
    preco_minimo: input.preco_minimo ?? null,
    margem_alvo: input.margem_alvo ?? null,
    margem_percent: input.margem_percent ?? null,
    estoque_atual: input.estoque_atual ?? 0,
    estoque_minimo: input.estoque_minimo ?? null,
    estoque_maximo: input.estoque_maximo ?? null,
    estoque_seguranca: input.estoque_seguranca ?? null,
    localizacao: input.localizacao ?? null,
    fornecedor_principal: input.fornecedor_principal ?? null,
    fornecedor_alternativo: input.fornecedor_alternativo ?? null,
    fornecedor_principal_id: input.fornecedor_principal_id ?? null,
    fornecedor_alternativo_id: input.fornecedor_alternativo_id ?? null,
    empresa_id: input.empresa_id ?? null,
    filial_id: input.filial_id ?? null,
    controla_estoque: input.controla_estoque ?? input.tipo !== "servico",
    controla_lote: input.controla_lote ?? false,
    controla_serie: input.controla_serie ?? false,
    controla_validade: input.controla_validade ?? false,
    observacoes: input.observacoes ?? null,
    ativo: input.ativo,
  };
}

export { toNumericInputValue };
