import { defineLibrary } from "./builder.ts";
import type { SegmentLibraryItem } from "./types.ts";

export const OFICINA_LIBRARY: SegmentLibraryItem[] = defineLibrary("oficina", [
  {
    category: "Revisão / Manutenção",
    defaultDurationMinutes: 60,
    recommendCount: 4,
    items: [
      { name: "Revisão básica", defaultDurationMinutes: 60 },
      { name: "Revisão completa", defaultDurationMinutes: 180 },
      { name: "Revisão preventiva", defaultDurationMinutes: 90 },
      { name: "Troca de óleo do motor", defaultDurationMinutes: 30 },
      "Troca de filtro de óleo",
      "Troca de filtro de ar",
      "Troca de filtro de combustível",
      "Troca de filtro de cabine",
      "Troca de fluido de freio",
      "Troca de fluido de arrefecimento",
      "Limpeza do sistema de arrefecimento",
      "Check-up geral",
      "Inspeção pré-viagem",
      "Inspeção pré-compra",
    ],
  },
  {
    category: "Freios",
    defaultDurationMinutes: 60,
    items: [
      "Troca de pastilhas dianteiras",
      "Troca de pastilhas traseiras",
      "Troca de discos de freio",
      "Troca de tambor/lona",
      "Sangria do sistema de freio",
      "Regulagem de freio",
      "Diagnóstico de freios",
    ],
  },
  {
    category: "Suspensão",
    defaultDurationMinutes: 90,
    items: [
      "Troca de amortecedores",
      "Troca de molas",
      "Troca de bandejas",
      "Troca de buchas",
      "Troca de pivôs",
      "Troca de bieletas",
      "Troca de terminais",
      "Diagnóstico de suspensão",
    ],
  },
  {
    category: "Direção",
    defaultDurationMinutes: 45,
    items: [
      "Alinhamento",
      "Balanceamento",
      "Cambagem",
      "Troca de terminal de direção",
      "Troca de caixa de direção",
      "Diagnóstico de direção",
    ],
  },
  {
    category: "Motor",
    defaultDurationMinutes: 60,
    items: [
      "Diagnóstico de motor",
      "Scanner automotivo",
      { name: "Troca de correia dentada", defaultDurationMinutes: 180 },
      "Troca de correia de acessórios",
      "Troca de velas",
      "Troca de cabos",
      "Limpeza de bicos",
      "Limpeza de TBI",
      "Teste de compressão",
      "Troca de junta",
      "Reparo de vazamento",
      {
        name: "Retífica / serviço de cabeçote",
        description: "Serviço externo de retífica ou cabeçote, quando aplicável.",
        recommended: false,
      },
    ],
  },
  {
    category: "Elétrica",
    defaultDurationMinutes: 40,
    items: [
      "Diagnóstico elétrico",
      "Troca de bateria",
      "Teste de bateria",
      "Teste de alternador",
      "Teste de motor de partida",
      "Troca de lâmpadas",
      "Reparo de chicote",
      "Instalação de acessórios",
    ],
  },
  {
    category: "Ar-condicionado",
    defaultDurationMinutes: 50,
    items: [
      "Higienização",
      "Recarga de gás",
      "Diagnóstico",
      "Troca de filtro de cabine",
      "Reparo do sistema",
    ],
  },
  {
    category: "Transmissão",
    defaultDurationMinutes: 90,
    items: [
      "Troca de óleo do câmbio",
      "Diagnóstico de câmbio",
      { name: "Troca de embreagem", defaultDurationMinutes: 180 },
      "Regulagem de embreagem",
    ],
  },
  {
    category: "Pneus",
    defaultDurationMinutes: 30,
    items: [
      "Troca de pneus",
      "Rodízio",
      "Reparo de pneu",
      "Calibragem",
      "Alinhamento",
      "Balanceamento",
    ],
  },
]);
