import type { ProductCapability } from "./capabilities.ts";
import { BASE_CAPABILITIES } from "./capabilities.ts";
import type { ProductSegmentId, SegmentProfile } from "./types.ts";
import { SEGMENT_ENGINE_VERSION } from "./types.ts";
import type { DespesaPresetId } from "../financeiro/despesa-presets.ts";
import type { BeneficiarioTipo } from "../financeiro/beneficiario-types.ts";

const ALL_PAYEES: readonly BeneficiarioTipo[] = [
  "fornecedor",
  "funcionario",
  "mecanico",
  "vendedor",
  "prestador",
  "locador",
  "concessionaria",
  "governo",
  "outro",
];

const SERVICE_PAYEES: readonly BeneficiarioTipo[] = [
  "fornecedor",
  "funcionario",
  "prestador",
  "locador",
  "concessionaria",
  "governo",
  "outro",
];

function cap(
  extra: ProductCapability[],
): ProductCapability[] {
  return [...new Set([...BASE_CAPABILITIES, ...extra])];
}

const OFICINA_FINANCE: readonly DespesaPresetId[] = [
  "salarios",
  "comissoes",
  "prestadores",
  "combustivel",
  "frete",
  "manutencao",
  "aluguel",
  "energia",
  "agua",
  "material_escritorio",
  "impostos",
  "outras",
];

const BARBEARIA_FINANCE: readonly DespesaPresetId[] = [
  "salarios",
  "comissoes",
  "aluguel",
  "energia",
  "agua",
  "marketing",
  "material_escritorio",
  "software",
  "outras",
];

const LAVA_FINANCE: readonly DespesaPresetId[] = [
  "salarios",
  "comissoes",
  "material_escritorio",
  "agua",
  "energia",
  "aluguel",
  "manutencao",
  "marketing",
  "outras",
];

const CONSULTORIA_FINANCE: readonly DespesaPresetId[] = [
  "prolabore",
  "prestadores",
  "software",
  "marketing",
  "contabilidade",
  "impostos",
  "aluguel",
  "internet",
  "outras",
];

const CLINICA_FINANCE: readonly DespesaPresetId[] = [
  "salarios",
  "comissoes",
  "material_escritorio",
  "aluguel",
  "energia",
  "software",
  "marketing",
  "impostos",
  "outras",
];

const ODONTO_FINANCE: readonly DespesaPresetId[] = [
  "salarios",
  "prestadores",
  "material_escritorio",
  "aluguel",
  "software",
  "contabilidade",
  "impostos",
  "outras",
];

export const SEGMENT_PROFILES: Record<ProductSegmentId, SegmentProfile> = {
  oficina: {
    id: "oficina",
    label: "Oficina Mecânica",
    shortDescription: "Clientes, veículos, OS, estoque e financeiro",
    version: SEGMENT_ENGINE_VERSION,
    capabilities: cap([
      "appointments",
      "vehicles",
      "work_orders",
      "workshop_mechanics",
      "professionals",
      "commissions",
      "inventory",
      "service_checklist",
      "sales",
      "purchases",
      "operations_board",
      "crm",
      "analytics",
      "integrations",
      "tax",
    ]),
    terminology: {
      customer: "Cliente",
      customers: "Clientes",
      professional: "Mecânico",
      professionals: "Mecânicos",
      workOrder: "Ordem de Serviço",
      catalog: "Serviços e Peças",
      appointment: "Agenda",
    },
    recommendedNavIds: [
      "ops-center",
      "dashboard",
      "search",
      "clients",
      "products",
      "inventory",
      "purchases",
      "sales",
      "work-orders",
      "agenda",
      "mechanics",
      "intelligence-hub",
      "tax-hub",
      "crm",
      "finance",
      "integrations",
      "analytics",
      "analytics-reports",
    ],
    defaultDashboard: "operacoes",
    financePresetIds: OFICINA_FINANCE,
    costCenterSuggestions: ["Oficina", "Recepção", "Estoque", "Administrativo"],
    beneficiarioTipos: ALL_PAYEES,
    onboardingHighlights: [
      "Ordens de serviço e veículos",
      "Mecânicos e comissões",
      "Estoque, compras e financeiro",
    ],
  },
  barbearia: {
    id: "barbearia",
    label: "Barbearia",
    shortDescription: "Agenda, profissionais, serviços e comissões",
    version: SEGMENT_ENGINE_VERSION,
    capabilities: cap([
      "appointments",
      "professionals",
      "commissions",
      "inventory",
      "sales",
      "recurring_services",
      "packages",
      "operations_board",
      "crm",
      "analytics",
    ]),
    terminology: {
      customer: "Cliente",
      customers: "Clientes",
      professional: "Barbeiro",
      professionals: "Barbeiros",
      workOrder: "Atendimento",
      catalog: "Serviços e produtos",
      appointment: "Agenda",
    },
    recommendedNavIds: [
      "ops-center",
      "dashboard",
      "clients",
      "products",
      "agenda",
      "mechanics",
      "sales",
      "inventory",
      "finance",
      "crm",
      "analytics-reports",
    ],
    defaultDashboard: "agenda",
    financePresetIds: BARBEARIA_FINANCE,
    costCenterSuggestions: ["Salão", "Recepção", "Administrativo"],
    beneficiarioTipos: SERVICE_PAYEES,
    onboardingHighlights: [
      "Agenda e profissionais",
      "Serviços, produtos e comissões",
      "Financeiro e recorrência",
    ],
  },
  lava_rapido: {
    id: "lava_rapido",
    label: "Lava-rápido / Estética automotiva",
    shortDescription: "Veículos, agenda, pacotes e checklist",
    version: SEGMENT_ENGINE_VERSION,
    capabilities: cap([
      "appointments",
      "vehicles",
      "professionals",
      "work_orders",
      "service_checklist",
      "recurring_services",
      "packages",
      "inventory",
      "sales",
      "operations_board",
      "crm",
      "analytics",
    ]),
    terminology: {
      customer: "Cliente",
      customers: "Clientes",
      professional: "Profissional",
      professionals: "Profissionais",
      workOrder: "Atendimento",
      catalog: "Pacotes e serviços",
      appointment: "Agenda",
    },
    recommendedNavIds: [
      "ops-center",
      "dashboard",
      "clients",
      "agenda",
      "mechanics",
      "work-orders",
      "products",
      "inventory",
      "sales",
      "finance",
      "crm",
      "analytics-reports",
    ],
    defaultDashboard: "operacoes",
    financePresetIds: LAVA_FINANCE,
    costCenterSuggestions: ["Boxes", "Estética", "Administrativo"],
    beneficiarioTipos: [...SERVICE_PAYEES, "mecanico"],
    onboardingHighlights: [
      "Agenda e veículos",
      "Checklist e pacotes",
      "Estoque e financeiro",
    ],
  },
  consultoria: {
    id: "consultoria",
    label: "Consultoria",
    shortDescription: "Clientes, CRM, agenda e financeiro",
    version: SEGMENT_ENGINE_VERSION,
    capabilities: cap([
      "appointments",
      "crm",
      "sales",
      "operations_board",
      "analytics",
      "integrations",
      "accounts_payable",
      "accounts_receivable",
    ]),
    terminology: {
      customer: "Cliente",
      customers: "Clientes",
      professional: "Consultor",
      professionals: "Consultores",
      workOrder: "Projeto / Entrega",
      catalog: "Serviços",
      appointment: "Agenda",
    },
    recommendedNavIds: [
      "ops-center",
      "dashboard",
      "search",
      "clients",
      "products",
      "sales",
      "agenda",
      "crm",
      "finance",
      "integrations",
      "analytics",
      "analytics-reports",
    ],
    defaultDashboard: "executivo",
    financePresetIds: CONSULTORIA_FINANCE,
    costCenterSuggestions: ["Consultoria", "Comercial", "Administrativo"],
    beneficiarioTipos: SERVICE_PAYEES,
    onboardingHighlights: [
      "CRM e clientes",
      "Agenda e entregas",
      "Contas a pagar e receber",
    ],
  },
  clinica_estetica: {
    id: "clinica_estetica",
    label: "Clínica de estética",
    shortDescription: "Agenda, profissionais, procedimentos e pacotes",
    version: SEGMENT_ENGINE_VERSION,
    capabilities: cap([
      "appointments",
      "professionals",
      "commissions",
      "inventory",
      "sales",
      "recurring_services",
      "packages",
      "operations_board",
      "crm",
      "analytics",
    ]),
    futureCapabilities: ["patient_records"],
    terminology: {
      customer: "Cliente",
      customers: "Clientes",
      professional: "Profissional",
      professionals: "Profissionais",
      workOrder: "Atendimento",
      catalog: "Procedimentos e pacotes",
      appointment: "Agenda",
    },
    recommendedNavIds: [
      "ops-center",
      "dashboard",
      "clients",
      "agenda",
      "mechanics",
      "products",
      "sales",
      "inventory",
      "finance",
      "crm",
      "analytics-reports",
    ],
    defaultDashboard: "agenda",
    financePresetIds: CLINICA_FINANCE,
    costCenterSuggestions: ["Atendimento", "Recepção", "Administrativo"],
    beneficiarioTipos: SERVICE_PAYEES,
    onboardingHighlights: [
      "Agenda e profissionais",
      "Procedimentos e pacotes",
      "Produtos e financeiro",
    ],
  },
  consultorio_odontologico: {
    id: "consultorio_odontologico",
    label: "Consultório odontológico",
    shortDescription: "Pacientes, agenda, procedimentos e financeiro",
    version: SEGMENT_ENGINE_VERSION,
    capabilities: cap([
      "appointments",
      "professionals",
      "sales",
      "operations_board",
      "crm",
      "analytics",
      "accounts_receivable",
    ]),
    futureCapabilities: ["patient_records", "treatment_plans"],
    terminology: {
      customer: "Paciente",
      customers: "Pacientes",
      professional: "Dentista",
      professionals: "Profissionais",
      workOrder: "Procedimento",
      catalog: "Procedimentos",
      appointment: "Agenda",
    },
    recommendedNavIds: [
      "ops-center",
      "dashboard",
      "clients",
      "agenda",
      "mechanics",
      "products",
      "finance",
      "crm",
      "analytics-reports",
      "sales",
    ],
    defaultDashboard: "agenda",
    financePresetIds: ODONTO_FINANCE,
    costCenterSuggestions: ["Consultório", "Recepção", "Administrativo"],
    beneficiarioTipos: SERVICE_PAYEES,
    onboardingHighlights: [
      "Pacientes e agenda",
      "Procedimentos e financeiro",
      "Contas a receber",
    ],
  },
};

export const DEFAULT_LEGACY_TERMINOLOGY: SegmentProfile["terminology"] = {
  customer: "Cliente",
  customers: "Clientes",
  professional: "Profissional",
  professionals: "Equipe",
  workOrder: "Ordem",
  catalog: "Catálogo",
  appointment: "Agenda",
};

export function getSegmentProfile(id: ProductSegmentId): SegmentProfile {
  return SEGMENT_PROFILES[id];
}
