/**
 * Catálogo estático do Design System (Gate 19.5).
 * Sem I/O · sem dados de negócio · fonte para showcase + testes.
 */

export const SHOWCASE_CATEGORIES = [
  { id: "brand", label: "Brand" },
  { id: "foundations", label: "Foundations" },
  { id: "typography", label: "Typography" },
  { id: "colors", label: "Colors" },
  { id: "spacing", label: "Spacing" },
  { id: "radius", label: "Radius" },
  { id: "shadows", label: "Shadows" },
  { id: "motion", label: "Motion" },
  { id: "icons", label: "Icons" },
  { id: "buttons", label: "Buttons" },
  { id: "inputs", label: "Inputs" },
  { id: "forms", label: "Form Controls" },
  { id: "badges", label: "Badges" },
  { id: "status", label: "Status" },
  { id: "cards", label: "Cards" },
  { id: "kpis", label: "KPIs" },
  { id: "panels", label: "Panels" },
  { id: "tables", label: "Tables" },
  { id: "filters", label: "Filters" },
  { id: "navigation", label: "Navigation" },
  { id: "header", label: "Header" },
  { id: "sidebar", label: "Sidebar" },
  { id: "dialogs", label: "Dialogs" },
  { id: "drawers", label: "Drawers" },
  { id: "loading", label: "Loading" },
  { id: "skeletons", label: "Skeletons" },
  { id: "empty", label: "Empty States" },
  { id: "errors", label: "Error States" },
  { id: "charts", label: "Charts" },
  { id: "executive-blocks", label: "Executive Blocks" },
  { id: "onboarding", label: "Onboarding" },
  { id: "legacy", label: "Legacy Audit" },
] as const;

export type ShowcaseCategoryId = (typeof SHOWCASE_CATEGORIES)[number]["id"];

export type ComponentStatus =
  | "oficial"
  | "experimental"
  | "legado"
  | "duplicado"
  | "orfao"
  | "deprecado"
  | "pendente";

export type CatalogComponent = {
  name: string;
  path: string;
  status: ComponentStatus;
  category: ShowcaseCategoryId;
  description: string;
  whenToUse: string;
  whenNotToUse: string;
  tokens: string[];
  codeSample: string;
  hasDemo: boolean;
};

export const OFFICIAL_COMPONENTS: CatalogComponent[] = [
  {
    name: "BrandMark",
    path: "components/brand/brand-mark.tsx",
    status: "oficial",
    category: "brand",
    description: "Monograma oficial da marca Gestão.",
    whenToUse: "Sidebar, header compacto, favicon textual.",
    whenNotToUse: "Não substituir o logo completo em splash/login.",
    tokens: ["--brand-graphite", "--brand-gold"],
    codeSample: `<BrandMark size="md" />`,
    hasDemo: true,
  },
  {
    name: "BrandLogo",
    path: "components/brand/brand-logo.tsx",
    status: "oficial",
    category: "brand",
    description: "Marca + nome + subtítulo/edition.",
    whenToUse: "Login, splash, headers institucionais.",
    whenNotToUse: "Não usar como título de página de negócio.",
    tokens: ["brandConfig", "gofTypography"],
    codeSample: `<BrandLogo markSize="lg" showEdition />`,
    hasDemo: true,
  },
  {
    name: "BrandSplash",
    path: "components/brand/brand-splash.tsx",
    status: "oficial",
    category: "loading",
    description: "Loading institucional unificado (Gate 19.4.1).",
    whenToUse: "Fallbacks de rota, Suspense de shell, auth loading.",
    whenNotToUse: "Não usar SkeletonCard legado em rotas.",
    tokens: ["brandAssets", "brand-progress", "gofMotion"],
    codeSample: `<BrandSplash label="Carregando…" className="min-h-[40vh]" />`,
    hasDemo: true,
  },
  {
    name: "ExecutivePage",
    path: "components/executive/ExecutivePage.tsx",
    status: "oficial",
    category: "foundations",
    description: "Container de página Enterprise.",
    whenToUse: "Toda tela migrada Wave 1+.",
    whenNotToUse: "Não aninhar páginas.",
    tokens: ["gofContainer", "gofSpaceY"],
    codeSample: `<ExecutivePage width="wide"><ExecutiveHeader title="…" /></ExecutivePage>`,
    hasDemo: true,
  },
  {
    name: "ExecutiveHeader",
    path: "components/executive/ExecutiveHeader.tsx",
    status: "oficial",
    category: "header",
    description: "Cabeçalho de módulo (título + ações).",
    whenToUse: "Topo de seção/módulo.",
    whenNotToUse: "Não duplicar greeting do AppHeader.",
    tokens: ["gofTypography", "gofCardHeader"],
    codeSample: `<ExecutiveHeader title="Dashboard" description="Visão do dia" />`,
    hasDemo: true,
  },
  {
    name: "ExecutiveSection",
    path: "components/executive/ExecutiveSection.tsx",
    status: "oficial",
    category: "foundations",
    description: "Seção com título, descrição e painel opcional.",
    whenToUse: "Blocos de conteúdo do dashboard/módulos.",
    whenNotToUse: "Não usar SectionCard legado.",
    tokens: ["gofTypography", "gofCardSurface"],
    codeSample: `<ExecutiveSection title="Score" panel>…</ExecutiveSection>`,
    hasDemo: true,
  },
  {
    name: "ExecutiveCard",
    path: "components/executive/ExecutiveCard.tsx",
    status: "oficial",
    category: "cards",
    description: "Card canônico com prioridade e padding.",
    whenToUse: "Containers interativos/informativos.",
    whenNotToUse: "Não criar card local com shadow arbitrária.",
    tokens: ["gofCardSurface", "gofRadius", "gofShadow"],
    codeSample: `<ExecutiveCard padding={20}>Conteúdo</ExecutiveCard>`,
    hasDemo: true,
  },
  {
    name: "MetricCard",
    path: "components/executive/MetricCard.tsx",
    status: "oficial",
    category: "kpis",
    description: "KPI oficial (label + valor + tom).",
    whenToUse: "Indicadores numéricos.",
    whenNotToUse: "Não inventar dados no showcase.",
    tokens: ["gofColors", "ExecutiveCard"],
    codeSample: `<MetricCard label="Realizado" value="R$ 12.400" tone="success" />`,
    hasDemo: true,
  },
  {
    name: "ExecutivePanel",
    path: "components/executive/ExecutivePanel.tsx",
    status: "oficial",
    category: "panels",
    description: "Painel com header/footer opcionais.",
    whenToUse: "Agrupar ações e conteúdo denso.",
    whenNotToUse: "Não substituir Section quando só há título.",
    tokens: ["gofCardSurface", "gofCardPadding"],
    codeSample: `<ExecutivePanel><ExecutivePanelHeader>…</ExecutivePanelHeader></ExecutivePanel>`,
    hasDemo: true,
  },
  {
    name: "ExecutiveBadge",
    path: "components/executive/ExecutiveBadge.tsx",
    status: "oficial",
    category: "badges",
    description: "Badge semântico (soft/solid/outline).",
    whenToUse: "Status, tags, meta do dia.",
    whenNotToUse: "Não usar Badge shadcn cru em telas migradas.",
    tokens: ["gofColors", "gofRadius"],
    codeSample: `<ExecutiveBadge tone="success" variant="soft">No ritmo</ExecutiveBadge>`,
    hasDemo: true,
  },
  {
    name: "ExecutiveButton",
    path: "components/executive/ExecutiveButton.tsx",
    status: "oficial",
    category: "buttons",
    description: "Botão com loading/disabled/focus Brand.",
    whenToUse: "CTAs em superfícies Executive.",
    whenNotToUse: "Não criar ActionButton paralelo.",
    tokens: ["gofFocusRing", "Button"],
    codeSample: `<ExecutiveButton loading={false}>Salvar</ExecutiveButton>`,
    hasDemo: true,
  },
  {
    name: "ExecutiveIconButton",
    path: "components/executive/ExecutiveIconButton.tsx",
    status: "oficial",
    category: "buttons",
    description: "Botão só ícone com hit target adequado.",
    whenToUse: "Ações compactas na toolbar.",
    whenNotToUse: "Sem aria-label.",
    tokens: ["gofFocusRing"],
    codeSample: `<ExecutiveIconButton aria-label="Atualizar" icon={RefreshCw} />`,
    hasDemo: true,
  },
  {
    name: "ExecutiveTable",
    path: "components/executive/ExecutiveTable.tsx",
    status: "oficial",
    category: "tables",
    description: "Tabela com empty/loading/sticky.",
    whenToUse: "Listagens Executive.",
    whenNotToUse: "Não montar com dados reais no showcase.",
    tokens: ["gofCardSurface", "ExecutiveEmptyState"],
    codeSample: `<ExecutiveTable columns={…} rows={[]} getRowId={(r) => r.id} />`,
    hasDemo: true,
  },
  {
    name: "ExecutiveFilter",
    path: "components/executive/ExecutiveFilter.tsx",
    status: "oficial",
    category: "filters",
    description: "Barra de filtros (role=search).",
    whenToUse: "Filtros de período/contexto.",
    whenNotToUse: "Não misturar formulários longos.",
    tokens: ["gofControl", "gofFocusRing"],
    codeSample: `<ExecutiveFilter><ExecutiveFilterField label="De">…</ExecutiveFilterField></ExecutiveFilter>`,
    hasDemo: true,
  },
  {
    name: "ExecutiveDivider",
    path: "components/executive/ExecutiveDivider.tsx",
    status: "oficial",
    category: "foundations",
    description: "Divisor opcional com label.",
    whenToUse: "Separar blocos densos.",
    whenNotToUse: "Não usar como card.",
    tokens: ["gofTypography"],
    codeSample: `<ExecutiveDivider label="Detalhes" />`,
    hasDemo: true,
  },
  {
    name: "ExecutiveLoading",
    path: "components/executive/ExecutiveLoading.tsx",
    status: "oficial",
    category: "loading",
    description: "Loading de bloco (não de rota).",
    whenToUse: "Suspense interno de seção.",
    whenNotToUse: "Rotas → BrandSplash.",
    tokens: ["gofMotion"],
    codeSample: `<ExecutiveLoading label="Carregando seção…" />`,
    hasDemo: true,
  },
  {
    name: "ExecutiveSkeleton",
    path: "components/executive/ExecutiveSkeleton.tsx",
    status: "oficial",
    category: "skeletons",
    description: "Shimmer oficial ≤1.6s.",
    whenToUse: "Placeholders de conteúdo.",
    whenNotToUse: "SkeletonCard legado.",
    tokens: ["gofMotion.skeleton"],
    codeSample: `<ExecutiveSkeleton heightClassName="h-8" widthClassName="w-1/2" />`,
    hasDemo: true,
  },
  {
    name: "ExecutiveEmptyState",
    path: "components/executive/ExecutiveEmptyState.tsx",
    status: "oficial",
    category: "empty",
    description: "Empty canônico Brand.",
    whenToUse: "Listas/módulos sem dados.",
    whenNotToUse: "Não inventar zeros como conteúdo.",
    tokens: ["gofSurface", "brandConfig"],
    codeSample: `<ExecutiveEmptyState title="Sem registros" description="…" />`,
    hasDemo: true,
  },
  {
    name: "ExecutiveStatus",
    path: "components/executive/ExecutiveStatus.tsx",
    status: "oficial",
    category: "status",
    description: "Chip de status semântico.",
    whenToUse: "Estados de saúde/meta.",
    whenNotToUse: "Não substituir Badge quando só há tag.",
    tokens: ["gofColors"],
    codeSample: `<ExecutiveStatus tone="warning">Atenção</ExecutiveStatus>`,
    hasDemo: true,
  },
  {
    name: "ExecutiveProgress",
    path: "components/executive/ExecutiveProgress.tsx",
    status: "oficial",
    category: "status",
    description: "Barra de progresso acessível.",
    whenToUse: "Atingimento de meta.",
    whenNotToUse: "Não usar blue-600 local.",
    tokens: ["gofColors.primary", "aria-valuenow"],
    codeSample: `<ExecutiveProgress value={72} />`,
    hasDemo: true,
  },
];

export const PRODUCT_BLOCKS: CatalogComponent[] = [
  {
    name: "ExecutiveKpiCard",
    path: "components/dashboard/executive/executive-kpi-card.tsx",
    status: "oficial",
    category: "executive-blocks",
    description: "KPI do Score do dia (Wave 1).",
    whenToUse: "Dashboard executivo.",
    whenNotToUse: "Showcase sem fixtures reais de faturamento.",
    tokens: ["gof*", "ExecutiveBadge"],
    codeSample: `// Ver dashboard-streaming · ResumoVendasHojeCards`,
    hasDemo: false,
  },
  {
    name: "ExecutiveDecisionCenter",
    path: "components/dashboard/executive/executive-decision-center.tsx",
    status: "oficial",
    category: "executive-blocks",
    description: "Centro de decisões inteligentes.",
    whenToUse: "Dashboard · decisões agrupadas.",
    whenNotToUse: "Não chamar compose no showcase.",
    tokens: ["ExecutiveEmptyState", "gof*"],
    codeSample: `// Montado em dashboard-streaming`,
    hasDemo: false,
  },
  {
    name: "ExecutiveFinancialCockpit",
    path: "components/dashboard/executive/executive-financial-cockpit.tsx",
    status: "oficial",
    category: "executive-blocks",
    description: "Cockpit financeiro executivo.",
    whenToUse: "Dashboard · bloco financeiro.",
    whenNotToUse: "Sem loaders de domínio aqui.",
    tokens: ["gof*"],
    codeSample: `// Montado em dashboard-streaming`,
    hasDemo: false,
  },
  {
    name: "ExecutiveAiCard",
    path: "components/dashboard/executive/executive-ai-card.tsx",
    status: "oficial",
    category: "executive-blocks",
    description: "Score IA Executiva.",
    whenToUse: "Dashboard · score da empresa.",
    whenNotToUse: "Não executar engine no showcase.",
    tokens: ["gof*"],
    codeSample: `// Suspense + buildExecutiveAiResult no dashboard`,
    hasDemo: false,
  },
  {
    name: "ExecutiveSummarySection",
    path: "components/dashboard/executive/executive-summary-section.tsx",
    status: "oficial",
    category: "executive-blocks",
    description: "Resumo executivo do dia.",
    whenToUse: "Dashboard · insights.",
    whenNotToUse: "Sem compose no showcase.",
    tokens: ["gof*"],
    codeSample: `// Montado em dashboard-streaming`,
    hasDemo: false,
  },
  {
    name: "ExecutiveActionPlanSection",
    path: "components/dashboard/executive/executive-action-plan-section.tsx",
    status: "oficial",
    category: "executive-blocks",
    description: "Plano de ação executivo.",
    whenToUse: "Dashboard · próximos passos.",
    whenNotToUse: "Sem dados inventados.",
    tokens: ["gof*"],
    codeSample: `// Montado em dashboard-streaming`,
    hasDemo: false,
  },
  {
    name: "DashboardQuickActions",
    path: "components/dashboard/dashboard-quick-actions.tsx",
    status: "oficial",
    category: "executive-blocks",
    description: "Ações rápidas Enterprise (OS, venda, cliente…).",
    whenToUse: "Bloco inicial do dashboard.",
    whenNotToUse: "Não persistir no banco.",
    tokens: ["gof*", "ExecutiveSection"],
    codeSample: `<DashboardQuickActions tenantSlug={slug} />`,
    hasDemo: true,
  },
  {
    name: "ImplantationChecklist",
    path: "components/onboarding/implantation-checklist.tsx",
    status: "oficial",
    category: "onboarding",
    description: "Checklist de implantação (empresa nova).",
    whenToUse: "Dashboard lead / onboarding.",
    whenNotToUse: "Não adicionar queries novas no showcase.",
    tokens: ["gof*", "brandConfig"],
    codeSample: `// Via OnboardingResumeCard`,
    hasDemo: false,
  },
  {
    name: "OnboardingTour",
    path: "components/onboarding/onboarding-tour.tsx",
    status: "oficial",
    category: "onboarding",
    description: "Tour opcional (Ignorar sempre).",
    whenToUse: "Primeiro acesso.",
    whenNotToUse: "Não bloquear tela.",
    tokens: ["gof*"],
    codeSample: `<OnboardingTour tenantSlug={slug} />`,
    hasDemo: false,
  },
];

export const LEGACY_AUDIT = [
  {
    name: "ex* tokens",
    filesHint: "lib/design-system/{colors,spacing,radius,shadow,typography,animations,glass}.ts",
    substitute: "gof* (foundation + primitives)",
    status: "pendente",
    risk: "médio",
    recommendation: "Migrar telas Wave a Wave; não expandir uso.",
    sprint: "19.x waves",
  },
  {
    name: "ds* tokens",
    filesHint: "lib/design-system/tokens.ts · dashboard legado",
    substitute: "gof*",
    status: "legado",
    risk: "médio",
    recommendation: "Remover após migração das listagens.",
    sprint: "Wave 3+",
  },
  {
    name: "blue-600 / blue-*",
    filesHint: "~25 arquivos (dashboard orphan, layout DnD, intelligence)",
    substitute: "var(--brand-gold) / gofColors.primary",
    status: "legado",
    risk: "baixo",
    recommendation: "Banir em PRs de UI.",
    sprint: "contínuo",
  },
  {
    name: "SkeletonCard",
    filesHint: "components/ui/skeleton-card.tsx · listagens app/",
    substitute: "BrandSplash (rota) · ExecutiveSkeleton (bloco)",
    status: "legado",
    risk: "baixo",
    recommendation: "Não usar em novos loadings.",
    sprint: "19.4.1+",
  },
  {
    name: "EmptyState (ui)",
    filesHint: "components/ui/empty-state.tsx",
    substitute: "ExecutiveEmptyState",
    status: "duplicado",
    risk: "baixo",
    recommendation: "Manter como wrapper Brand até migração total.",
    sprint: "Wave 2–3",
  },
  {
    name: "ExecutiveHeroV2 / HojePanel / HeatmapV2",
    filesHint: "components/dashboard/executive/executive-*-v2.tsx",
    substitute: "blocos Wave 1 em dashboard-streaming",
    status: "orfao",
    risk: "baixo (não montados)",
    recommendation: "Remover em Wave dedicada de limpeza.",
    sprint: "Wave 3 cleanup",
  },
  {
    name: "dashboard/comercial/**",
    filesHint: "components/dashboard/comercial/**",
    substitute: "CommercialIntelligence* em vendas",
    status: "deprecado",
    risk: "baixo",
    recommendation: "Não reativar; remover após confirmação.",
    sprint: "Wave 3 cleanup",
  },
  {
    name: "copilot / action-center",
    filesHint: "components/executive/copilot · action-center",
    substitute: "DecisionCenter + ActionPlan (Wave 1)",
    status: "orfao",
    risk: "baixo",
    recommendation: "Deprecar exports públicos.",
    sprint: "Wave 3 cleanup",
  },
  {
    name: "ActionButton / SaveButton / CancelButton",
    filesHint: "components/ui/action-button.tsx etc.",
    substitute: "ExecutiveButton / Button",
    status: "duplicado",
    risk: "baixo",
    recommendation: "Congelar; migrar callers.",
    sprint: "contínuo",
  },
] as const;

export const VIEWPORTS = [
  { id: "mobile", label: "Mobile", width: 390 },
  { id: "tablet", label: "Tablet", width: 768 },
  { id: "notebook", label: "Notebook", width: 1366 },
  { id: "desktop", label: "Desktop", width: 1440 },
  { id: "wide", label: "1920", width: 1920 },
] as const;

export const DESIGN_SYSTEM_ROUTE_SUFFIX = "design-system";

export function designSystemPath(tenantSlug: string) {
  return `/${tenantSlug}/${DESIGN_SYSTEM_ROUTE_SUFFIX}`;
}

export const SHOWCASE_ACCESS_ROLES = ["owner", "admin"] as const;
